# Generated by Django 5.2.8 on 2025-12-03 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
    ]
